apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: worker-pv-claim
    namespace: dispatcher
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
