apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatcher
  namespace: dispatcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-dispatcher
  namespace: dispatcher
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-dispatcher-binding
  namespace: dispatcher
subjects:
- kind: ServiceAccount
  name: dispatcher
  namespace: dispatcher
roleRef:
  kind: Role
  name: job-dispatcher
  apiGroup: rbac.authorization.k8s.io
