from __future__ import annotations

APP_NAME = "dispatcher"
POD_RESTART_POLICY = "Never"
TTL_AFTER_FINISHED = 60
JOB_API_VERSION = "batch/v1"
WATCH_SERVER_TIMEOUT = 3600
WATCH_CLIENT_TIMEOUT = 60
NAMESPACE = "dispatcher"
MAX_POD_LOG_SIZE = 4_096
BROKER_POOL_LIMIT = 25
WORKER_PREFETCH_MULTIPLIER = 1
